### ISSUE TITLE
Arduino Nmea parser - ATSAMD21 - RTCZero 

### ISSUE THREAD

**Issue by jmanuelv** [107-systems/107-Arduino-NMEA-Parser#42] opened 2021-06-01 20:02 UTC
Hello, I am a user of your library, I have a project where I use a gps quectel L80-R and my development board is based on the ATSamD21 microcontroller, the Arduino Nmea parser library works very well for me, I also use the RTC Zero library but I think It generates conflict for me when using it together with the Nmea Parser, you know perhaps why, I appreciate your information, sorry for my English, I use a translator, I hope you understand me.

**Comment by aentinger** [comment] 2021-06-02 09:32
Hi @jmanuelv :wave:

This is an open source library which means all of the work going is volunteer effort only and not being paid. As my time is limited I'll be only answering free support requests on my own time line and by my own choice. Your error description is very vague, if you want to increase the chance of me helping you, you should work on improving it considerably.

**Comment by Angeles111254** [comment] 2021-06-02 20:46
Hello, I also have the same problem as Juan Manuel. When the samd21 goes into sleep mode, after it wakes up it no longer performs latitude and longitude readings.

here below I leave the RTC base code, what I think is that when putting the micro in sleep mode it generates a conflict with the nmea library.


[RTCzero_led.txt](https://github.com/107-systems/107-Arduino-NMEA-Parser/files/6587355/RTCzero_led.txt)

**Comment by aentinger** [comment] 2021-06-03 06:25
Which version of the library are you running? Can you provide a complete code example which exhibits the problematic behaviour?

**Comment by Angeles111254** [comment] 2021-06-03 06:38
the versions are:
RTCzero version 1.6.0
Arduino NMEA parser 1.1.2`

[rtczero_nmea.txt](https://github.com/107-systems/107-Arduino-NMEA-Parser/files/6589476/rtczero_nmea.txt)

`

**Comment by Angeles111254** [comment] 2021-06-03 06:41
the versions are:
RTCzero version 1.6.0
Arduino NMEA parser 1.1.2

**Comment by Angeles111254** [comment] 2021-06-03 06:48
without sleeping the samd21 the nmea library allows the GPS readings, after giving it standby mode, the readings are no longer made. I think that at that moment it disables something in the nmea library which generates this error. Thanks for the help, you are very attentive.
[rtczero_nmea.txt](https://github.com/107-systems/107-Arduino-NMEA-Parser/files/6589530/rtczero_nmea.txt)

**Comment by aentinger** [comment] 2023-08-09 12:33
@Angeles111254 did you find the cause for your issue? If so I'd be curious to hear about it. But I'll close this issue for now, I've got zero bandwidth to investigate the issue myself.

**Closed by aentinger** 2023-08-09 12:33 UTC
Labels: status: waiting for information, topic: firmware, type: support
